server:
  port: 9192

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TeacHKal/spring-microservices-config-server
          clone-on-start: true